#!/bin/sh
pretty=$(hyprctl getoption general:gaps_in | awk 'NR==2{print $2}')
if [ "$pretty" != 0 ] ; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0;\
        keyword master:no_gaps_when_only 1"
    exit
fi
hyprctl reload
